 development:
   adapter: postgresql
   encoding: unicode
   database: humble_dev
   pool: 5
   username: humbly
   password: password1

 test:
   adapter: postgresql
   encoding: unicode
   database: humble_test
   pool: 5
   username: humbly
   password: password1
